name: Update IXP Data and Notify Webhook

on:
  schedule:
    - cron: '0 1 * * *'  # Runs every day at 00:00
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    name: 'IXP Data Update and Webhook Notification'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Run custom notify-webhook action'
        uses: ./.github/actions/notify-webhook
        with:
          CHANGES: $(git diff HEAD~1 HEAD)
          LAST_COMMIT: $(git rev-parse HEAD)
          PREVIOUS_COMMIT: $(git rev-parse HEAD~1)
          WEBHOOK_URL: 'YOUR_WEBHOOK_URL_HERE'

      - name: Send Payload to Webhook
        run: |
          WEBHOOK_URL="${{ inputs.WEBHOOK_URL }}"
          PAYLOAD=$(echo $PAYLOAD)
          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" $WEBHOOK_URL
