name: Notify Webhook
on:
  schedule:
    - cron: '0 1 * * *'  # Runs every day at 01:00
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    name: 'IXP Data Update and Webhook Notification'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Webhook URL
        run: |
          WEBHOOK_URL="https://mattermost.ripe.net/hooks/nwqyskg5gbdxze78ppa3st37by"
          echo "WEBHOOK_URL=$WEBHOOK_URL" >> $GITHUB_ENV

      - name: Identify Changes on Specific File
        run: |
          FILE_NAME="data/ixps.json"
          CHANGES=$(git diff HEAD^1 HEAD -- $FILE_NAME)

          if [[ -n "$CHANGES" ]]; then
            PAYLOAD="{\"last_commit\": \"$LAST_COMMIT\", \"previous_commit\": \"$PREVIOUS_COMMIT\", \"changes\": \"Changes detected in $FILE_NAME\"}"
            echo "PAYLOAD=$PAYLOAD" >> $GITHUB_ENV
          else
            echo "No changes detected in $FILE_NAME"
          fi

      - name: Send Payload to Webhook
        run: |
          WEBHOOK_URL=${{ env.WEBHOOK_URL }}
          PAYLOAD=$(echo $PAYLOAD)
          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" $WEBHOOK_URL
