name: Update IXP Data and Notify Webhook

on:
  schedule:
    # Runs "Every day at 00:00" (see https://crontab.guru)
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packages
        run: |
           pip3 install beautifulsoup4
           pip3 install requests

      - name: Run get_peeringdb_ixps.py
        run: python3 get_peeringdb_ixps.py --output-peeringlan "${{ secrets.API_KEY_PEERINGDB }}"

      - name: Run get_he_ixps.py
        run: python3 get_he_ixps.py

      - name: Run get_pch_ixps.py
        run: python3 get_pch_ixps.py

      - name: Run merge_ixp_data.py
        run: python3 merge_ixp_data.py

      # Commit changes to the repository
      - name: Commit changes
        if: success()
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Workflow
          author_email: actions@github.com
          message: 'Updating IXPs'
          add: 'data/*.json'
